### ISSUE TITLE
Get internal posts and associated templates working

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#6]
- Department news carousel (latest 5 or 6 items is fine)
- Post single template
- Post archive page and associated "See More" or "See All" on the department HP under the carousel

**Comment by gregoryspragginsjr** [comment]
@bwaltz support for internal posts by category should now work as of: https://github.com/ColbyCommunications/colby-college-theme/commit/151a57a23ffb964eb18125dc5b3faf2acb48450c Will be amending your fields in the CMS shortly, but please remind me if you dont seem them soon

**Comment by bwaltz** [comment]
@gregoryspragginsjr I think this looks good. You can check it out here:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/

Hopefully I did everything right.

I see everything minus the "See More" button at the bottom of the News section which should bring you to the archive page for that category.

**Comment by gregoryspragginsjr** [comment]
@bwaltz The `See All` button should now be popping up as of a recent commit. I also realize I missed the actual posts index / archive for categories, and have pushed a change for that as well. We should be good on that front, but give it another look. Also, be advised that the See All button now overrides any context button results coming from the CMS if `render_posts` is selected.

If additional context is needed (heading, subheading and paragraph), I recommend adding it manually as you might not necessarily want these to pull category descriptions and title as they are done on single post pages. We can discuss further if needed.

**Comment by bwaltz** [comment]
@gregoryspragginsjr this still doesn't work. For some reason, it is pulling in `art department` instead of the slug, which happens to be just `art`.

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/category/art/

**Comment by gregoryspragginsjr** [comment]
@bwaltz This is working as intended (pulling in the category `name` instead of the `slug`) which would typically be the approach for these. I do not recommend using the slug for these headings as we'll then have to integrate contingencies for dealing with dashes and forced uppercases which. If you'd like it to display as `Art`, then we'd want to simply change the actual category name (currently `Art Department`)
